### ISSUE TITLE
Ver 1.4.7 CRC does not match on arduino IDE v1.6.9

### ISSUE THREAD

**Issue by aa18514** [ivanseidel/DueTimer#53]
When trying to update or install the DueTimer library via the libraries manager in the arduino IDE I get the following error:

`CRC doesn't match. File is corrupted.
java.lang.RuntimeException: java.lang.Exception: CRC doesn't match. File is corrupted.
    at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$12(LibraryManagerUI.java:231)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: CRC doesn't match. File is corrupted.
    at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:77)
    at cc.arduino.contributions.libraries.LibraryInstaller.install(LibraryInstaller.java:97)
    at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$12(LibraryManagerUI.java:227)
    ... 1 more
`

Is this a problem on my side or of the library?

**Comment by ivanseidel** [comment]
Problem seems to be resolved in `1.8.5`
